-- Query 1: Delivery and Order Details
SELECT
    D.DELIVERY_ID,
    DA.AGENT_NAME AS AGENT,
    DA.AGENT_JOB,
    O.ORDER_ID,
    C.CUSTOMER_NAME AS CUSTOMER,
    C.ADDRESS,
    D.STATUS AS DELIVERY_STATUS,
    D.ESTIMATED_TIME_MINUTES AS ETA
FROM
    DELIVERY D
JOIN
    DELIVERY_AGENT DA ON D.AGENT_ID = DA.AGENT_ID
JOIN
    ORDERS O ON D.ORDER_NO = O.ORDER_ID
JOIN
    CUSTOMER C ON O.CUSTOMER_ID = C.CUSTOMER_ID
ORDER BY
    D.DELIVERY_ID;

-- Query 2: Orders and Regulations
SELECT
    O.ORDER_ID,
    C.CUSTOMER_NAME,
    O.AMOUNT AS ORDER_AMOUNT,
    R.DISCOUNTCODE,
    R.PAYABLE_AMOUNT AS PAYABLE_AFTER_DISCOUNT,
    R.TAX
FROM
    ORDERS O
LEFT JOIN
    REGULATIONS R ON O.ORDER_ID = R.O_NO
JOIN
    CUSTOMER C ON O.CUSTOMER_ID = C.CUSTOMER_ID
ORDER BY
    O.ORDER_ID;

-- Query 3: Revenue of Restaurants
SELECT
    R.RESTAURANT_ID,
    R.R_NAME AS RESTAURANT,
    RE.START_DATE,
    RE.END_DATE,
    RE.TOTALSALE AS TOTAL_SALES
FROM
    REVENUE RE
JOIN
    RESTAURANTS R ON RE.R_ID = R.RESTAURANT_ID
WHERE
    RE.START_DATE >= SYSDATE - 30 -- Last 30 days
ORDER BY
    RE.TOTALSALE DESC;

-- Query 4: Low-rated Feedback
SELECT
    C.CUSTOMER_NAME,
    O.ORDER_ID,
    R.REVIEW_NO,
    R.RATING,
    R.FEEDBACK
FROM
    REVIEW R
JOIN
    ORDERS O ON R.ORDER_ID = O.ORDER_ID
JOIN
    CUSTOMER C ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE
    R.RATING < 3 -- Low-rated feedback
ORDER BY
    R.RATING ASC, R.REVIEW_NO;

-- Query 5: Orders and Payment Details
SELECT
    C.CUSTOMER_NAME,
    O.ORDER_ID,
    O.ORDER_STATUS,
    P.P_METHOD AS PAYMENT_METHOD,
    P.P_DATE AS PAYMENT_DATE,
    P.PAYABLE_AMOUNT
FROM
    CUSTOMER C
JOIN
    ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
LEFT JOIN
    PAYMENT P ON O.ORDER_ID = P.O_ID
ORDER BY
    C.CUSTOMER_NAME, O.ORDER_ID;

-- Query 6: Active Promotions
SELECT
    P.PROMO_ID,
    PD.PROMO_NAME AS PROMOTION,
    P.PROMOCODE,
    R.R_NAME AS RESTAURANT,
    PD.ACTIVATIONDATE,
    PD.LASTDATE
FROM
    PROMOTIONS P
JOIN
    RESTAURANTS R ON P.R_ID = R.RESTAURANT_ID
JOIN
    PROMOTIONS_DETAILS PD ON P.PROMOCODE = PD.PROMO_CODE
WHERE
    PD.ACTIVATIONDATE <= SYSDATE
    AND PD.LASTDATE >= SYSDATE
ORDER BY
    PD.LASTDATE ASC;

-- View: Active Promotions
CREATE OR REPLACE VIEW ACTIVE_PROMOTIONS AS
SELECT
    P.PROMO_ID,
    R.R_NAME AS RESTAURANT_NAME,
    PD.PROMO_NAME,
    P.PROMOCODE,
    PD.ACTIVATIONDATE,
    PD.LASTDATE
FROM
    PROMOTIONS P
JOIN
    RESTAURANTS R ON P.R_ID = R.RESTAURANT_ID
JOIN
    PROMOTIONS_DETAILS PD ON P.PROMOCODE = PD.PROMO_CODE
WHERE
    PD.LASTDATE >= SYSDATE
    AND PD.ACTIVATIONDATE <= SYSDATE
ORDER BY
    PD.LASTDATE ASC;

-- Query 7: Delivery Agents with More than 5 Deliveries
SELECT
    D.DELIVERY_ID,
    D.ORDER_NO,
    DA.AGENT_NAME,
    D.STATUS
FROM
    DELIVERY D
JOIN
    DELIVERY_AGENT DA ON D.AGENT_ID = DA.AGENT_ID
WHERE
    D.AGENT_ID IN (
        SELECT
            AGENT_ID
        FROM
            DELIVERY
        GROUP BY
            AGENT_ID
        HAVING
            COUNT(*) > 5
    );

-- Query 8: Delivery Agents with Recent Deliveries
SELECT
    AGENT_NAME,
    AGENT_JOB,
    HIREDATE
FROM
    DELIVERY_AGENT
WHERE
    AGENT_ID IN (
        SELECT
            AGENT_ID
        FROM
            DELIVERY
        WHERE
            DEPARTURE_DATE >= SYSDATE - 7
    );
