CREATE TABLE DELIVERY_AGENT (
    AGENT_ID NUMBER(2),
    AGENT_NAME VARCHAR2(50) CONSTRAINT AGENT_NAME_NN NOT NULL,
    AGENT_JOB VARCHAR2(20) CONSTRAINT AGENT_JOB_NN NOT NULL,
    HIREDATE DATE DEFAULT SYSDATE,
    CONSTRAINT AGENT_PK PRIMARY KEY (AGENT_ID)
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID NUMBER(2),
    CUSTOMER_NAME VARCHAR2(50) CONSTRAINT CUSTOMER_NAME_NN NOT NULL,
    ADDRESS VARCHAR2(255) CONSTRAINT CUSTOMER_ADDRESS_NN NOT NULL,
    CUSTOMER_EMAIL VARCHAR2(255) CONSTRAINT CUSTOMER_EMAIL_NN NOT NULL,
    CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE ORDERS (
    ORDER_ID NUMBER(2),
    CUSTOMER_ID NUMBER(2),
    ORDER_STATUS VARCHAR2(20) CONSTRAINT ORDER_STATUS_NN NOT NULL,
    AMOUNT NUMBER(3,2) CONSTRAINT ORDER_AMOUNT_NN NOT NULL,
    CONSTRAINT ORDER_PK PRIMARY KEY (ORDER_ID),
    CONSTRAINT ORDER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
);

ALTER TABLE ORDERS
MODIFY AMOUNT NUMBER(5,2);

CREATE TABLE DELIVERY (
    DELIVERY_ID NUMBER(2) CONSTRAINT DELIVERY_PK PRIMARY KEY,
    AGENT_ID NUMBER(2),
    DEPARTURE_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(50) CONSTRAINT DELIVERY_STATUS_NN NOT NULL,
    ORDER_NO NUMBER(2),
    ESTIMATED_TIME_MINUTES NUMBER(3) CONSTRAINT DELIVERY_TIME_NN NOT NULL,
    CONSTRAINT DELIVERY_AGENT_FK FOREIGN KEY (AGENT_ID) REFERENCES DELIVERY_AGENT (AGENT_ID),
    CONSTRAINT DELIVERY_ORDER_FK FOREIGN KEY (ORDER_NO) REFERENCES ORDERS (ORDER_ID)
);

CREATE TABLE REVIEW (
    REVIEW_NO NUMBER(2) CONSTRAINT REVIEW_PK PRIMARY KEY,
    ORDER_ID NUMBER(2),
    RATING NUMBER(1) CONSTRAINT RATING_CHECK CHECK (RATING BETWEEN 1 AND 5),
    FEEDBACK VARCHAR2(255),
    CONSTRAINT REVIEW_ORDER_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID)
);

CREATE TABLE REGULATIONS (
    REG_ID NUMBER(2) CONSTRAINT REGULATIONS_PK PRIMARY KEY,
    O_NO NUMBER(2),
    DISCOUNTCODE VARCHAR2(10),
    PAYABLE_AMOUNT NUMBER CONSTRAINT REGULATIONS_AMOUNT_PAY_NN NOT NULL,
    TAX NUMBER CONSTRAINT REGULATIONS_TAX_NN NOT NULL
);

CREATE TABLE ORDER_REGULATIONS (
    O_NO NUMBER(2),
    REG_ID NUMBER(2),
    CONSTRAINT ORDER_REG_PK PRIMARY KEY (O_NO, REG_ID),
    CONSTRAINT ORDER_REG_ORDER_FK FOREIGN KEY (O_NO) REFERENCES ORDERS (ORDER_ID),
    CONSTRAINT ORDER_REG_REG_FK FOREIGN KEY (REG_ID) REFERENCES REGULATIONS (REG_ID)
);

ALTER TABLE REGULATIONS
ADD CONSTRAINT REGULATIONS_ORDER_FK
FOREIGN KEY (O_NO) REFERENCES ORDERS (ORDER_ID);

CREATE TABLE PAYMENT (
    P_NO NUMBER(2),
    P_METHOD VARCHAR2(50) CONSTRAINT PAYMENT_METHOD_NN NOT NULL,
    P_DATE DATE DEFAULT SYSDATE,
    O_ID NUMBER(2),
    PAYABLE_AMOUNT NUMBER CONSTRAINT PAYMENT_AMOUNT_NN NOT NULL,
    CONSTRAINT PAYMENT_PK PRIMARY KEY (P_NO, O_ID),
    CONSTRAINT PAYMENT_ORDER_FK FOREIGN KEY (O_ID) REFERENCES ORDERS (ORDER_ID)
);

CREATE TABLE ORDERITEMS (
    O_NO NUMBER(2),
    ITEM_NO NUMBER(2),
    QUANTITY NUMBER,
    PRICE NUMBER,
    CONSTRAINT ORDERITEMS_PK PRIMARY KEY (O_NO, ITEM_NO),
    CONSTRAINT ORDERITEMS_ORDER_FK FOREIGN KEY (O_NO) REFERENCES ORDERS (ORDER_ID)
);

CREATE TABLE ITEMS (
    ITEM_NO NUMBER(2) CONSTRAINT ITEM_PK PRIMARY KEY,
    ITEM_NAME VARCHAR2(50) CONSTRAINT ITEM_NAME_NN NOT NULL
);

ALTER TABLE ORDERITEMS
ADD CONSTRAINT ORDERITEMS_ITEM_FK FOREIGN KEY (ITEM_NO) REFERENCES ITEMS (ITEM_NO);

CREATE TABLE RESTAURANT_ITEMS (
    ITEM_NUMBER NUMBER(2),
    RESTAURANT_ID NUMBER(2),
    PRICE NUMBER CONSTRAINT RESTAURANT_ITEMS_PRICE_CHECK CHECK (PRICE NOT IN (NULL, 0)),
    AVAILIBILITY_STATUS VARCHAR(20),
    LASTUPDATED DATE DEFAULT SYSDATE,
    CONSTRAINT RESTAURANT_ITEMS_PK PRIMARY KEY (ITEM_NUMBER, RESTAURANT_ID)
);

CREATE TABLE RESTAURANTS (
    RESTAURANT_ID NUMBER(2) CONSTRAINT RESTAURANT_PK PRIMARY KEY,
    R_NAME VARCHAR2(50) CONSTRAINT REST_NAME_NN NOT NULL,
    AREALOC VARCHAR2(50) CONSTRAINT REST_LOC_NN NOT NULL,
    OPERATIONAL_HRS NUMBER(2)
);

CREATE TABLE RESTAURANTS_CONTACTS (
    R_ID NUMBER(2),
    R_CONTACT VARCHAR2(15),
    CONSTRAINT RESTAURANTS_CONTACTS_PK PRIMARY KEY (R_ID, R_CONTACT),
    CONSTRAINT RESTAURANTS_CONTACTS_FK FOREIGN KEY (R_ID) REFERENCES RESTAURANTS (RESTAURANT_ID)
);

ALTER TABLE RESTAURANTS_CONTACTS
MODIFY (R_CONTACT NOT NULL);

ALTER TABLE RESTAURANT_ITEMS
ADD CONSTRAINT ITEMS_REST_FK FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (RESTAURANT_ID);

ALTER TABLE ITEMS
ADD CONSTRAINT ITEMS_RESTAURANT_ID_FK FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (RESTAURANT_ID);

CREATE TABLE PROMOTIONS (
    PROMO_ID NUMBER(2) CONSTRAINT PROMOTIONS_PK PRIMARY KEY,
    R_ID NUMBER(2) CONSTRAINT PROMO_FK FOREIGN KEY (R_ID) REFERENCES RESTAURANTS (RESTAURANT_ID),
    PROMOCODE VARCHAR2(10),
    CONSTRAINT uq_promo_code UNIQUE (PROMOCODE)
);

CREATE TABLE PROMOTIONS_DETAILS (
    PROMO_CODE VARCHAR2(10) PRIMARY KEY,
    PROMO_NAME VARCHAR2(255) NOT NULL,
    ACTIVATIONDATE DATE NOT NULL,
    LASTDATE DATE NOT NULL,
    CONSTRAINT FK_PROMO_CODE FOREIGN KEY (PROMO_CODE) REFERENCES PROMOTIONS (PROMO_CODE)
);

CREATE TABLE REVENUE (
    REVENUE_ID NUMBER(2),
    R_ID NUMBER(2),
    CONSTRAINT REVENUE_PK PRIMARY KEY (REVENUE_ID, R_ID),
    CONSTRAINT REVENUE_FK FOREIGN KEY (R_ID) REFERENCES RESTAURANTS (RESTAURANT_ID),
    START_DATE DATE DEFAULT SYSDATE,
    END_DATE DATE DEFAULT SYSDATE,
    TOTALSALE NUMBER CONSTRAINT REVENUE_TOTALSALE_NN NOT NULL
);
